name: C/C++ CI

on: 
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'
  pull_request:

jobs:
  build-windows:
    runs-on: windows-2022
  
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Build release 
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bspguy-windows
        path: build/Release

  build-linux:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    
    - name: Download and install dependencies
      run: |
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev libglew-dev libxxf86vm-dev

    - name: Build release
      run: |
        mkdir build; cd build
        cmake .. -DCMAKE_BUILD_TYPE=RELEASE
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bspguy-linux
        path: build/bspguy

  create-release:
    name: Create GitHub Release
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    permissions:
      contents: write

    steps:
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: bspguy-windows
          path: bspguy-windows

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: bspguy-linux
          path: bspguy-linux

      - name: Zip Artifacts
        run: |
          zip -r bspguy-windows.zip bspguy-windows
          zip -r bspguy-linux.zip bspguy-linux

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bspguy-windows.zip
            bspguy-linux.zip
          generate_release_notes: true